### ISSUE TITLE
Generic cloning method for operations

### ISSUE THREAD

**Issue by sonirico** [FEOMedia/artemis-odb-orion#15]
Sometimes might be useful to define a class for storing common-used operations under an alias, above all for those which may require bigger parametrization options. I have been implementing a `.cpy()` method for several operations, however I think that having Operation implementing Cloneable would be the right way. Might it be possible to do? Taking in account that they work under a pooling engine...

**Comment by junkdog** [comment]
it's already possible using `OperationSystem::copy`, e.g.:


```java
	private void pressOperation(Entity e) {
		Operation op = interactionMapper.get(e).onTouch;
		if (op != null) { // as operation are "consumed" upon registration
			operations.copy(op).register(e);
		}
	}
```

**Comment by junkdog** [comment]
it's how `RepeatOperation` works too:

```java
private OperationTree replaceChild(OperationTree node) {
	RepeatOperation op = (RepeatOperation) node.operation;

	OperationTree oldChild = node.children().pop();

	Operation copy = operations.copy(op.repeated);
	node.add(copy.toNode());
	node.initialize(operations, op.entityId);

	// reclaiming objects
	oldChild.clear();
	return node.children().first();
}
```

**Comment by sonirico** [comment]
Oops! Didn't know about that.

**Comment by junkdog** [comment]
> Oops! Didn't know about that.

it ought to be documented somewhere
