### ISSUE TITLE
xy() safety

### ISSUE THREAD

**Issue by DaanVanYperen** [FEOMedia/artemis-odb-orion#17]
Consider implementing a small ring buffer or pool bound to the processing lifecycle. See #16.

**Comment by DaanVanYperen** [comment]
Using this myself.

```java
public abstract class XY {
    public static final int POOL_SIZE = 64;

    private final static Vector3[] pool = new Vector3[POOL_SIZE];
    private static int index = 0;

    static {
        for (int i = 0; i < POOL_SIZE; i++) {
            pool[i] = new Vector3();
        }
    }

    /**
     * Obtain temporary vector3. Should not escape local context.
     */
    public static Vector3 xy() {
        return getFromPool().set(0, 0, 0);
    }

    /**
     * Obtain temporary vector3. Should not escape local context.
     */
    public static Vector3 xy(Vector3 source) {
        return getFromPool().set(source);
    }

    /**
     * Obtain temporary vector3. Should not escape local context.
     */
    public static Vector3 xy(float x, float y) {
        return getFromPool().set(x, y, 0);
    }

    /**
     * Obtain temporary vector3. Should not escape local context.
     */
    public static Vector3 xy(float x, float y, float z) {
        return getFromPool().set(x, y, z);
    }

    private static Vector3 getFromPool() {
        return pool[(index = (index + 1) % POOL_SIZE)];
    }
}
```

**Comment by DaanVanYperen** [comment]
For operations yes, I'm using it in places where I need a vector for temp math. Still playing around with it, eventually I'll use it inside and outside a loop and break my game. ;)

**Comment by sonirico** [comment]
Great! Two questions. 
- How do I get these last changes using Gradle?
- What is that [hex num](https://github.com/FEOMedia/artemis-odb-orion/commit/95cd8e1cc0102aa79953fe941ad1a757d8c36357#diff-0924d77789f3fa4ec53b6be8c6fb7d3bR597) for?

**Comment by junkdog** [comment]
> How do I get these last changes using Gradle?

a bit inconvenient, you still need to pull and rebuild with `mvn clean install`. I can try to get the first release out next week; I think it might be a quieter week at work.

> What is that hex num for?

It's binary, not hexadecimal. it's mostly a silly/stupid micro-optimization to avoid doing a division/modulo, by constraining the array size to a power of two.

```
0 = 0b0000 & 0b0011 = 0b0000
1 = 0b0001 & 0b0011 = 0b0001
2 = 0b0010 & 0b0011 = 0b0010
3 = 0b0011 & 0b0011 = 0b0011
4 = 0b0100 & 0b0011 = 0b0000
5 = 0b0101 & 0b0011 = 0b0001
6 = 0b0110 & 0b0011 = 0b0010
7 = 0b0111 & 0b0011 = 0b0011
8 = 0b1000 & 0b0011 = 0b0000
```

**Comment by sonirico** [comment]
@junkdog oh! I thought that feature was only available in languages like C. `0b` for binaries and `0x` for hex... So I could do things like this?
```java
boolean  isOdd (int number) {
    return number  & 1 != 0; // 1 or 0b1?
} 
```
